sudo: required
services: 
  - docker 

before_install:
  - docker build -t parulkumarpal/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true parulkumarpal/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "Docker_travis"
  env: "Dockertravis-env"
  bucket_name: "elasticbeanstalk-ap-south-1-887346248474"
  bucket_path: "Docker_travis"
  on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY